image: thatisnomoon-docker-local.jfrog.io/ambidexter/deployer:latest

variables:
  NPM_REPOSITORY: //thatisnomoon.jfrog.io/thatisnomoon/api/npm/npm-local/
  MUTATION_TEST_THRESHOLD: 80

stages:
  - test
  - mutation_test
  - code_quality
  - publish

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test
  coverage: '/All files\s+\|\s+([\d.]+)/'
  artifacts:
    paths:
      - build
      - node_modules
    expire_in: 1 hr

mutation_test:
  stage: mutation_test
  script:
    - apk add --no-cache bc~=1.07
    - echo "Mutation testing with Stryker..."
    - MUTATION_TEST_SCORE=$(NODE_NO_WARNINGS=1 npm run stryker | awk '/^All files/{print $4}')
    - echo "Score is $MUTATION_TEST_SCORE%; desired threshold is $MUTATION_TEST_THRESHOLD%"
    - ([[ $(echo "$MUTATION_TEST_SCORE >= $MUTATION_TEST_THRESHOLD" | bc) = 1 ]])

codequality:
  stage: code_quality
  script:
    - sonar-scanner
        -Dsonar.login=$SONARQUBE_TOKEN
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.gitlab.json_mode=CODECLIMATE
        -Dsonar.gitlab.user_token=$SONARQUBES_GITLAB_ACCESS_TOKEN
        -Dsonar.gitlab.project_id=$CI_PROJECT_ID
        -Dsonar.branch.name=$CI_COMMIT_REF_NAME

publish:
  stage: publish
  script:
    - npm --registry https:${NPM_REPOSITORY} publish
  only:
    - master
