image: thatisnomoon-docker-local.jfrog.io/ambidexter/deployer:latest

variables:
  NPM_REPOSITORY: //thatisnomoon.jfrog.io/thatisnomoon/api/npm/npm-local/

stages:
  - test
  - code_quality
  - publish

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test
  coverage: '/All files\s+\|\s+([\d.]+)/'
  artifacts:
    paths:
      - build

codequality:
  stage: code_quality
  script:
    - sonar-scanner
        -Dsonar.login=$SONARQUBE_TOKEN
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.gitlab.json_mode=CODECLIMATE
        -Dsonar.gitlab.user_token=$SONARQUBES_GITLAB_ACCESS_TOKEN
        -Dsonar.gitlab.project_id=$CI_PROJECT_ID

publish:
  stage: publish
  script:
    - npm --registry https:${NPM_REPOSITORY} publish
  only:
    - master
