language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

before_script:
- yarn global add codecov

script:
- yarn run lint
- yarn test
- codecov

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
