language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn run lint
  - yarn test

deploy:
  - provider: npm
  - email: jonas.holtkamp@senacor.com
  - api_key: 6105bc89-c927-4183-a597-598d8ef6d4ff
  on:
    tags: true

# coverage: '/All files\s+\|\s+([\d.]+)/'